#!/bin/bash

# to address (fresh?) bids-validator whining about incorrect datetime format

cd "$(dirname $0)/.."

find * -iname '*_scans.tsv' | xargs sed -i -E 's/([0-9]{4}-[0-9]{2}-[0-9]{2}) ([0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{6})/\1T\2/g'
