#!/bin/bash
#
# This follows https://github.com/spatialtopology/spacetop-prep/issues/86#issuecomment-2147883561
# but with some fixes (e.g. no --swap was desired actually)
# 
set -eu
set -x

code/rename_file --all-extensions sub-0016/ses-01/fmap/sub-0016_ses-01_acq-mb8_dir-ap_run{+-PVC-run-04,-02}_epi.json
code/rename_file --all-extensions sub-0016/ses-01/fmap/sub-0016_ses-01_acq-mb8_dir-pa_run{=-PVS-run-04,-02}_epi.json

code/rename_file --all-extensions sub-0016/ses-01/fmap/sub-0016_ses-01_acq-mb8_dir-ap_run{-07,-03}_epi.json
code/rename_file --all-extensions sub-0016/ses-01/fmap/sub-0016_ses-01_acq-mb8_dir-pa_run{-07,-03}_epi.json

for d in ap pa; do
    code/rename_file --all-extensions sub-0017/ses-01/fmap/sub-0017_ses-01_acq-mb8_dir-${d}{_alignvideos,}_run-02_epi.json
    code/rename_file --all-extensions sub-0017/ses-01/fmap/sub-0017_ses-01_acq-mb8_dir-${d}_run-{02,03}_epi.json
    code/rename_file --all-extensions sub-0017/ses-01/fmap/sub-0017_ses-01_acq-mb8_dir-${d}_run-{07,02}_epi.json
done

code/rename_file --swap --all-extensions sub-0025/ses-03/func/sub-0025_ses-03_task-social_acq-mb8{_51,}_run-03_sbref.json
rm -f sub-0025/ses-03/func/sub-0025_ses-03_task-social_acq-mb8*_51*
